### ISSUE TITLE
Commands Smartfriends

### ISSUE THREAD

**Issue by og-gh** [LoPablo/SchellenbergApi#2]
Hi Pascal,

thanks for sharing this API.
I'm trying to integrate it into my OpenHab system.
Currently I try to understand the code and try to add some more commands into CommandFactory.
How did you get the information about the supported SMARTFRIENDs commands and parameters, like "createAllNewInfoCmd"?
Thanks for your feedback!

og-gh

**Comment by LoPablo** [comment]
HI, what du you mean by command. Do you mean commands for controlling a device?

**Comment by og-gh** [comment]
Hi, yes.
Commands known by the bridge.

**Comment by LoPablo** [comment]
Unfortunately, I don't have access to a Smartfriends or Schellenberg Gateway anymore so the following is from memory only:

The Gateway itself basically send everything for the GUI in the apps so show over the API. This includes every popup-window and every device the app should display. When the "AllNewInfo" is requested, the gateway sends every device, it's class and possible device values over the API. From there on you can only set values. 
So for example if you want to roll down a shutter, you would look into the device info, see which values are valid and set the device value accordingly. 

I can't remember if there were any other commands to issue to the gateway. There were commands for answering to popup messages which i didn't implement.

**Comment by LoPablo** [comment]
In the CommandFactry you can see all the other possible API Responses or commands i didn't implement.
```//TODO: implementation nedded

//class executeDeviceCmdCmd extends Command{
//    constructor(){
//        super('')
//    }
//}

//class newDeviceCmd extends Command{
//    constructor(){
//        super('')
//    }
//}

//class changeDeviceCmd extends Command{
//    constructor(){
//        super('')
//    }
//}

//class changeRoomCmd extends Command{
//    constructor(){
//        super('')
//    }
//}

//class deleteRoomCmd extends Command{
//    constructor(){
//        super('')
//    }
//}

//class newSwitchingSequenceCmd extends Command{
//    constructor(){
//        super('')
//    }
//}

//class changeSwitchingSequenceCmd extends Command{
//    constructor(){
//        super('')
//    }
//}

//class deleteSwitchingSequenceCmd extends Command{
//    constructor(){
//        super('')
//    }
//}

//class activateSwitchingSequenceCmd extends Command{
//    constructor(){
//        super('')
//    }
//}```

**Comment by og-gh** [comment]
Many thanks for those details!
